### ISSUE TITLE
which version of tensorflow is should be?

### ISSUE THREAD

**Issue by SeekPoint** [siddk/entity-network#4]
maybe share some procedure on how to reproduce is good

**Comment by siddk** [comment]
Sure - sorry about that.

This should work on TF Version >=1.0. If this is not the case, let me know. 

As for running it: `python run.py --task_id <TASK_ID>` from the top-level directory should work. This will train the model from scratch, validating every so often, and after it trains for 200 epochs will then evaluate on the test data.

To start fresh, you may need to clear out the checkpoints/ directory.

Let me know if there are any problems at all!

**Comment by SeekPoint** [comment]
I realized it also need tflearn, thanks
