### ISSUE TITLE
A portion of the data will never be trained/evaluated

### ISSUE THREAD

**Issue by filipemtz** [siddk/entity-network#7]
There is a small issue, but I think it won't change the reported results.

In lines 80, and 129, you do:
    for start, end in zip(range(0, n, bsz), range(bsz, n, bsz)):

If n is not a multiple of batch size, a small portion of the data in the end will never be trained/processed.
I think the correct would be something like: 

    n_batches = n / bsz + (1 if n % bsz != 0 else 0)
    for step in range(n_batches):
        start = step * bsz
        end = min((step + 1) * bsz, n)

**Comment by siddk** [comment]
Yup - that's pretty much expected, in the case of this code though, I'm not going to be missing more than 32 examples, which is pretty negligible.
